# Generated by Django 3.2.20 on 2023-09-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
