# Generated by Django 3.2.20 on 2023-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0006_alter_settingsmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='logo',
            field=models.FileField(upload_to='sitelogo/'),
        ),
    ]
