# Generated by Django 3.2.20 on 2023-09-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='property',
            new_name='prouct_property',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='coverImage',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
