# Generated by Django 3.2.20 on 2023-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0002_auto_20230906_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sell_state',
            field=models.CharField(choices=[('BEST', 'BEST'), ('DEALS', 'DEALS'), ('ALL', 'ALL')], default='ALL', max_length=9),
        ),
    ]
