# Generated by Django 3.2.20 on 2023-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_id',
            field=models.CharField(max_length=36, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='provider_order_id',
            field=models.CharField(max_length=40, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='signature_id',
            field=models.CharField(max_length=128, verbose_name='Signature ID'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
