# Generated by Django 3.2.20 on 2023-09-23 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordermanager', '0003_auto_20230920_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='orderby',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accountmanager.user'),
            preserve_default=False,
        ),
    ]
