# Generated by Django 3.2.20 on 2023-09-24 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0005_ordermodel_orderquentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductsmodel',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='ordermanager.ordermodel'),
        ),
    ]
