# Generated by Django 3.2.20 on 2023-09-23 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0003_auto_20230903_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=200)),
                ('Mobilenumber', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('Flat_House_no_Building_Apartment', models.CharField(max_length=200)),
                ('Area_Street_Sector_Village', models.CharField(max_length=200)),
                ('Landmark', models.CharField(max_length=200)),
                ('Town_City', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
