# Generated by Django 3.2.20 on 2023-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0004_shippmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippmentmodel',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
